server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/entry_payment?createDatabaseIfNotExist=true&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=Gani143gani@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
